# Generated by Django 4.0.5 on 2022-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrestadorDeServio',
            new_name='PrestadorDeServico',
        ),
        migrations.DeleteModel(
            name='Predio',
        ),
        migrations.AddField(
            model_name='carro',
            name='numeroDaVaga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='numeroDoApartamento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
