# Generated by Django 4.0.4 on 2022-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0002_rename_prestadordeservio_prestadordeservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='numeroDoApartamento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
