# Generated by Django 4.0.4 on 2022-06-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0003_visitante_numerodoapartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadordeservico',
            name='numeroDoApartamento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
